services:
  crewai:
    build:
        context: backend
        dockerfile: Dockerfile
    ports:
    - mode: ingress
      target: 3000
      published: 3000
    environment:
      - CREWAI_TRACING_ENABLED=true
      - GEMINI_API_KEY=